# Site settings
title: Aviral Dasgupta
description: Aviral Dasgupta's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aviraldg.com" # the base hostname & protocol for your site
twitter_username: aviraldg
github_username:  aviraldg

# Build settings
markdown: kramdown
